version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: FDio:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: stable/2009
    upstream: FDio:stable/2009        # Required. Can be a branch in the same forked repo.
    mergeMethod: hardreset
    assignees:              # Optional
      - ondrej-fabry
#    reviewers:              # Optional
#      - wei
label: "upstream sync"  # Optional

