name: Sync Upstream

on:
  schedule:
#    - cron: '0 0 * * *'

jobs:
  sync-master:
    name: Sync master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    
    
#     - uses: TG908/fork-sync@v1.1
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        owner: FDio
#        base: master
#        head: master
#        merge_method: rebase
#        pr_title: Sync master
